### ISSUE TITLE
[BUG] Cargo install of Ungoliant not working

### ISSUE THREAD

**Issue by kirianguiller** [oscar-corpus/ungoliant#40]
**Describe the bug**
Disclaimer : I'm sorry if the bug I face can be solve easily in some way, but I'm not a RUST developer and didn't find on stackoverflow or similar website the error I face

When running Ungoliant (`ungoliant -h` for instance), I get the following message : 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ungoliant-0.1.0/src/main.rs:10:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It works when installing from --git, so you might want to check/update the ungoliant repo on rust hub. (git version of ungoliant is 1.0.0 whereas cargo version is 0.1.0)

**To Reproduce**
1. Install cargo  + rust (https://doc.rust-lang.org/cargo/getting-started/installation.html)
2. Install Ungoliant with Cargo : `cargo install ungoliant`
3. Run Ungoliant : `ungoliant -h`

**Expected behavior**
Ungoliant working

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04

Thanks a lot !

**Comment by Uinelj** [comment]
Hello and thank you for your report! 

The version uploaded at crates.io is (very) old and is not functional at all. 
The latest version of Ungoliant relies on crates that have not yet been pushed to crates.io, this making our push impossible, which in turn makes the binary unavailable through `cargo install`. 

I opened an issue in the repository of the related crate: https://github.com/oscar-corpus/ungoliant/issues/17

I'll see what I can do to either disable the `cargo install` for the time being or find a way to make the issue more visible.
