### ISSUE TITLE
[Question] Different multilingual identification methods

### ISSUE THREAD

**Issue by codedecde** [oscar-corpus/ungoliant#50]
Hi 
Thank you so much for making this available ! 
I had a question regarding the two different multilingual identification strategies mentioned in the code: StrictMultilingual and Multilingual.
Specifically, would it be possible to share why the StrictMultilingual strategy was preferred for dataset creation, and if there was any benchmarking done (downstream performance / human annotation / eyeballing results) to say one is better than the other ?
Would be grateful for any input on this : )

Thank you !

**Comment by Uinelj** [comment]
Hello!

`Multilingual` has been implemented before `StrictMultilingual`, and (if I recall correcltly) yielded results that were not sufficiently balanced in terms of "content by language", and had some issues with tiny documents. 

`StrictMultilingual` ensures that you have a document that holds approximately the same minimum amount of data for each language, while keeping a threshold for non identified content.  

While developing the two versions I did some eyeballing results and found a general better balance (and lower file size) using `StrictMultilingual` so we kept this one, and the performance cost seems marginal enough that it did not change drastically our corpus generation times. The `multilingual` subcorpus is now ~12GB (which is quite big compared to the median subcorpus size) and we may change/adapt the process following user feedback

However I agree (and it has been a subject before) that we should have some human-annotated test corpus to control results :)

**Comment by codedecde** [comment]
Thank you for the response @Uinelj !
The one issue that I noticed in my experiments with the StrictMultilingual filter was that especially for documents that are bi-lingual, and FastText makes mistakes / incorrectly categorises some sentences as belonging to another language, the document is no longer classified as multilingual. 

Eg: For an en - es document, FasText classifies  ~45% of sentences as en,  ~45% of documents as es, and 5% as it (usually incorrect). Then, by the strict filter logic, because it < 25%, the document is no longer classified as multilingual. 

I have not looked at tiny documents w.r.t the Multilingual filter, but that is definitely a great point.
