### ISSUE TITLE
Feature `std_rng` depends on `rand_hc` which is not an optional dependency

### ISSUE THREAD

**Issue by DavidNemeskey** [oscar-corpus/ungoliant#55]
**Describe the bug**
Cannot install Ungoliant:
```
$ cargo install --verbose ungoliant
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing ungoliant v1.2.3
error: failed to compile `ungoliant v1.2.3`, intermediate artifacts can be found at `/tmp/cargo-install.dSby1MuzbHhE`

Caused by:
  failed to parse registry's information for: rand

Caused by:
  Feature `std_rng` depends on `rand_hc` which is not an optional dependency.
```

**Desktop (please complete the following information):**
 - OS: Linux 5.4.0-117-generic #132-Ubuntu SMP  x86_64 GNU/Linux
 - Versions:
   - Ungoliant: 1.2.3
   - cargo: 0.19.0

**Additional context**
I installed rust into a Conda environment via `conda install -c pkgw-forge cargo`. It's really bare-bones:
```
$ conda list
# packages in environment at /home/ndavid/miniconda3/envs/rust:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
ca-certificates           2022.4.26            h06a4308_0  
cargo                     0.19.0                        0    pkgw-forge
curl                      7.61.0               h84994c4_0  
libcurl                   7.61.0               h1ad7b7a_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libssh2                   1.8.0                h9cfc8f7_4  
openssl                   1.0.2u               h7b6447c_0  
zlib                      1.2.12               h7f8727e_2
```

**Comment by Uinelj** [comment]
Hello!

I've tried to install cargo via conda to reproduce the error, to no avail.
However, `conda list` and the [package page](https://anaconda.org/pkgw-forge/cargo) on conda site shows that the cargo version is `0.19.0` (more than 4 years ago), whereas the most recent one is `1.61.0`. 

It seems that conda has a more recent version of rust [here](https://anaconda.org/conda-forge/rust). Alternatively, you could either use a [container-based](https://hub.docker.com/_/rust) solution, or install rust directly using [rustup.rs](https://rustup.rs). 

Let me know if you need more help with this or if you could get it to work. 
Edit: It seems that the recent versions of rust hosted at Conda are still a little bit old,

**Comment by DavidNemeskey** [comment]
@Uinelj thanks, I completely missed that. I looked up "conda install cargo" and it lead to [this page](https://anaconda.org/pkgw-forge/cargo); and I didn't realize it was an outdated version. I installed the latest `rust` version (and `cmake`, and the latest `gcc`, ...), and with it, I managed to compile `ungoliant` in the end. Thank you!
